/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
import * as TEndPoint from "./TEndPoint";
export interface ITAINodeLocationArgs {
    aiNodeId: number;
    internalEndPoint: TEndPoint.TEndPoint;
}
export class TAINodeLocation {
    public aiNodeId: number;
    public internalEndPoint: TEndPoint.TEndPoint;
    constructor(args: ITAINodeLocationArgs) {
        if (args != null && args.aiNodeId != null) {
            this.aiNodeId = args.aiNodeId;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[aiNodeId] is unset!");
        }
        if (args != null && args.internalEndPoint != null) {
            this.internalEndPoint = args.internalEndPoint;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[internalEndPoint] is unset!");
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("TAINodeLocation");
        if (this.aiNodeId != null) {
            output.writeFieldBegin("aiNodeId", thrift.Thrift.Type.I32, 1);
            output.writeI32(this.aiNodeId);
            output.writeFieldEnd();
        }
        if (this.internalEndPoint != null) {
            output.writeFieldBegin("internalEndPoint", thrift.Thrift.Type.STRUCT, 2);
            this.internalEndPoint.write(output);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): TAINodeLocation {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_1: number = input.readI32();
                        _args.aiNodeId = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.STRUCT) {
                        const value_2: TEndPoint.TEndPoint = TEndPoint.TEndPoint.read(input);
                        _args.internalEndPoint = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        if (_args.aiNodeId !== undefined && _args.internalEndPoint !== undefined) {
            return new TAINodeLocation(_args);
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Unable to read TAINodeLocation from input");
        }
    }
}
