/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
export interface ITEndPointArgs {
    ip: string;
    port: number;
}
export class TEndPoint {
    public ip: string;
    public port: number;
    constructor(args: ITEndPointArgs) {
        if (args != null && args.ip != null) {
            this.ip = args.ip;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[ip] is unset!");
        }
        if (args != null && args.port != null) {
            this.port = args.port;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[port] is unset!");
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("TEndPoint");
        if (this.ip != null) {
            output.writeFieldBegin("ip", thrift.Thrift.Type.STRING, 1);
            output.writeString(this.ip);
            output.writeFieldEnd();
        }
        if (this.port != null) {
            output.writeFieldBegin("port", thrift.Thrift.Type.I32, 2);
            output.writeI32(this.port);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): TEndPoint {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_1: string = input.readString();
                        _args.ip = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_2: number = input.readI32();
                        _args.port = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        if (_args.ip !== undefined && _args.port !== undefined) {
            return new TEndPoint(_args);
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Unable to read TEndPoint from input");
        }
    }
}
