/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
export enum TRegionMigrateFailedType {
    AddPeerFailed = 0,
    RemovePeerFailed = 1,
    RemoveConsensusGroupFailed = 2,
    DeleteRegionFailed = 3,
    CreateRegionFailed = 4,
    Disconnect = 5
}
