/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
export enum TRegionMaintainTaskStatus {
    TASK_NOT_EXIST = 0,
    PROCESSING = 1,
    SUCCESS = 2,
    FAIL = 3
}
