/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import Int64 = require("node-int64");
import * as thrift from "thrift";
export interface ITSetTTLReqArgs {
    pathPattern: Array<string>;
    TTL: number | Int64;
    isDataBase: boolean;
}
export class TSetTTLReq {
    public pathPattern: Array<string>;
    public TTL: Int64;
    public isDataBase: boolean;
    constructor(args: ITSetTTLReqArgs) {
        if (args != null && args.pathPattern != null) {
            this.pathPattern = args.pathPattern;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[pathPattern] is unset!");
        }
        if (args != null && args.TTL != null) {
            if (typeof args.TTL === "number") {
                this.TTL = new Int64(args.TTL);
            }
            else {
                this.TTL = args.TTL;
            }
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[TTL] is unset!");
        }
        if (args != null && args.isDataBase != null) {
            this.isDataBase = args.isDataBase;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[isDataBase] is unset!");
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("TSetTTLReq");
        if (this.pathPattern != null) {
            output.writeFieldBegin("pathPattern", thrift.Thrift.Type.LIST, 1);
            output.writeListBegin(thrift.Thrift.Type.STRING, this.pathPattern.length);
            this.pathPattern.forEach((value_1: string): void => {
                output.writeString(value_1);
            });
            output.writeListEnd();
            output.writeFieldEnd();
        }
        if (this.TTL != null) {
            output.writeFieldBegin("TTL", thrift.Thrift.Type.I64, 2);
            output.writeI64(this.TTL);
            output.writeFieldEnd();
        }
        if (this.isDataBase != null) {
            output.writeFieldBegin("isDataBase", thrift.Thrift.Type.BOOL, 3);
            output.writeBool(this.isDataBase);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): TSetTTLReq {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.LIST) {
                        const value_2: Array<string> = new Array<string>();
                        const metadata_1: thrift.TList = input.readListBegin();
                        const size_1: number = metadata_1.size;
                        for (let i_1: number = 0; i_1 < size_1; i_1++) {
                            const value_3: string = input.readString();
                            value_2.push(value_3);
                        }
                        input.readListEnd();
                        _args.pathPattern = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_4: Int64 = input.readI64();
                        _args.TTL = value_4;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_5: boolean = input.readBool();
                        _args.isDataBase = value_5;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        if (_args.pathPattern !== undefined && _args.TTL !== undefined && _args.isDataBase !== undefined) {
            return new TSetTTLReq(_args);
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Unable to read TSetTTLReq from input");
        }
    }
}
