/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import Int64 = require("node-int64");
import * as thrift from "thrift";
export interface ITSpaceQuotaArgs {
    diskSize?: number | Int64;
    deviceNum?: number | Int64;
    timeserieNum?: number | Int64;
}
export class TSpaceQuota {
    public diskSize?: Int64;
    public deviceNum?: Int64;
    public timeserieNum?: Int64;
    constructor(args?: ITSpaceQuotaArgs) {
        if (args != null && args.diskSize != null) {
            if (typeof args.diskSize === "number") {
                this.diskSize = new Int64(args.diskSize);
            }
            else {
                this.diskSize = args.diskSize;
            }
        }
        if (args != null && args.deviceNum != null) {
            if (typeof args.deviceNum === "number") {
                this.deviceNum = new Int64(args.deviceNum);
            }
            else {
                this.deviceNum = args.deviceNum;
            }
        }
        if (args != null && args.timeserieNum != null) {
            if (typeof args.timeserieNum === "number") {
                this.timeserieNum = new Int64(args.timeserieNum);
            }
            else {
                this.timeserieNum = args.timeserieNum;
            }
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("TSpaceQuota");
        if (this.diskSize != null) {
            output.writeFieldBegin("diskSize", thrift.Thrift.Type.I64, 1);
            output.writeI64(this.diskSize);
            output.writeFieldEnd();
        }
        if (this.deviceNum != null) {
            output.writeFieldBegin("deviceNum", thrift.Thrift.Type.I64, 2);
            output.writeI64(this.deviceNum);
            output.writeFieldEnd();
        }
        if (this.timeserieNum != null) {
            output.writeFieldBegin("timeserieNum", thrift.Thrift.Type.I64, 3);
            output.writeI64(this.timeserieNum);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): TSpaceQuota {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_1: Int64 = input.readI64();
                        _args.diskSize = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_2: Int64 = input.readI64();
                        _args.deviceNum = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_3: Int64 = input.readI64();
                        _args.timeserieNum = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new TSpaceQuota(_args);
    }
}
