/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
export interface ITActiveTriggerInstanceReqArgs {
    triggerName: string;
}
export class TActiveTriggerInstanceReq {
    public triggerName: string;
    constructor(args: ITActiveTriggerInstanceReqArgs) {
        if (args != null && args.triggerName != null) {
            this.triggerName = args.triggerName;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[triggerName] is unset!");
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("TActiveTriggerInstanceReq");
        if (this.triggerName != null) {
            output.writeFieldBegin("triggerName", thrift.Thrift.Type.STRING, 1);
            output.writeString(this.triggerName);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): TActiveTriggerInstanceReq {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_1: string = input.readString();
                        _args.triggerName = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        if (_args.triggerName !== undefined) {
            return new TActiveTriggerInstanceReq(_args);
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Unable to read TActiveTriggerInstanceReq from input");
        }
    }
}
