/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
import * as org_apache_iotdb_common_rpc_thrift from "./../../../common/rpc/thrift";
export interface ITCheckTimeSeriesExistenceReqArgs {
    patternTree: Buffer;
    schemaRegionIdList: Array<org_apache_iotdb_common_rpc_thrift.TConsensusGroupId>;
}
export class TCheckTimeSeriesExistenceReq {
    public patternTree: Buffer;
    public schemaRegionIdList: Array<org_apache_iotdb_common_rpc_thrift.TConsensusGroupId>;
    constructor(args: ITCheckTimeSeriesExistenceReqArgs) {
        if (args != null && args.patternTree != null) {
            this.patternTree = args.patternTree;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[patternTree] is unset!");
        }
        if (args != null && args.schemaRegionIdList != null) {
            this.schemaRegionIdList = args.schemaRegionIdList;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[schemaRegionIdList] is unset!");
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("TCheckTimeSeriesExistenceReq");
        if (this.patternTree != null) {
            output.writeFieldBegin("patternTree", thrift.Thrift.Type.STRING, 1);
            output.writeBinary(this.patternTree);
            output.writeFieldEnd();
        }
        if (this.schemaRegionIdList != null) {
            output.writeFieldBegin("schemaRegionIdList", thrift.Thrift.Type.LIST, 2);
            output.writeListBegin(thrift.Thrift.Type.STRUCT, this.schemaRegionIdList.length);
            this.schemaRegionIdList.forEach((value_1: org_apache_iotdb_common_rpc_thrift.TConsensusGroupId): void => {
                value_1.write(output);
            });
            output.writeListEnd();
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): TCheckTimeSeriesExistenceReq {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_2: Buffer = input.readBinary();
                        _args.patternTree = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.LIST) {
                        const value_3: Array<org_apache_iotdb_common_rpc_thrift.TConsensusGroupId> = new Array<org_apache_iotdb_common_rpc_thrift.TConsensusGroupId>();
                        const metadata_1: thrift.TList = input.readListBegin();
                        const size_1: number = metadata_1.size;
                        for (let i_1: number = 0; i_1 < size_1; i_1++) {
                            const value_4: org_apache_iotdb_common_rpc_thrift.TConsensusGroupId = org_apache_iotdb_common_rpc_thrift.TConsensusGroupId.read(input);
                            value_3.push(value_4);
                        }
                        input.readListEnd();
                        _args.schemaRegionIdList = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        if (_args.patternTree !== undefined && _args.schemaRegionIdList !== undefined) {
            return new TCheckTimeSeriesExistenceReq(_args);
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Unable to read TCheckTimeSeriesExistenceReq from input");
        }
    }
}
