/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
import * as org_apache_iotdb_common_rpc_thrift from "./../../../common/rpc/thrift";
export interface ITDeleteDataForDeleteSchemaReqArgs {
    dataRegionIdList: Array<org_apache_iotdb_common_rpc_thrift.TConsensusGroupId>;
    pathPatternTree: Buffer;
    isGeneratedByPipe?: boolean;
}
export class TDeleteDataForDeleteSchemaReq {
    public dataRegionIdList: Array<org_apache_iotdb_common_rpc_thrift.TConsensusGroupId>;
    public pathPatternTree: Buffer;
    public isGeneratedByPipe?: boolean;
    constructor(args: ITDeleteDataForDeleteSchemaReqArgs) {
        if (args != null && args.dataRegionIdList != null) {
            this.dataRegionIdList = args.dataRegionIdList;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[dataRegionIdList] is unset!");
        }
        if (args != null && args.pathPatternTree != null) {
            this.pathPatternTree = args.pathPatternTree;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[pathPatternTree] is unset!");
        }
        if (args != null && args.isGeneratedByPipe != null) {
            this.isGeneratedByPipe = args.isGeneratedByPipe;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("TDeleteDataForDeleteSchemaReq");
        if (this.dataRegionIdList != null) {
            output.writeFieldBegin("dataRegionIdList", thrift.Thrift.Type.LIST, 1);
            output.writeListBegin(thrift.Thrift.Type.STRUCT, this.dataRegionIdList.length);
            this.dataRegionIdList.forEach((value_1: org_apache_iotdb_common_rpc_thrift.TConsensusGroupId): void => {
                value_1.write(output);
            });
            output.writeListEnd();
            output.writeFieldEnd();
        }
        if (this.pathPatternTree != null) {
            output.writeFieldBegin("pathPatternTree", thrift.Thrift.Type.STRING, 2);
            output.writeBinary(this.pathPatternTree);
            output.writeFieldEnd();
        }
        if (this.isGeneratedByPipe != null) {
            output.writeFieldBegin("isGeneratedByPipe", thrift.Thrift.Type.BOOL, 3);
            output.writeBool(this.isGeneratedByPipe);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): TDeleteDataForDeleteSchemaReq {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.LIST) {
                        const value_2: Array<org_apache_iotdb_common_rpc_thrift.TConsensusGroupId> = new Array<org_apache_iotdb_common_rpc_thrift.TConsensusGroupId>();
                        const metadata_1: thrift.TList = input.readListBegin();
                        const size_1: number = metadata_1.size;
                        for (let i_1: number = 0; i_1 < size_1; i_1++) {
                            const value_3: org_apache_iotdb_common_rpc_thrift.TConsensusGroupId = org_apache_iotdb_common_rpc_thrift.TConsensusGroupId.read(input);
                            value_2.push(value_3);
                        }
                        input.readListEnd();
                        _args.dataRegionIdList = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_4: Buffer = input.readBinary();
                        _args.pathPatternTree = value_4;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_5: boolean = input.readBool();
                        _args.isGeneratedByPipe = value_5;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        if (_args.dataRegionIdList !== undefined && _args.pathPatternTree !== undefined) {
            return new TDeleteDataForDeleteSchemaReq(_args);
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Unable to read TDeleteDataForDeleteSchemaReq from input");
        }
    }
}
