/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
import * as TFragmentInstanceId from "./TFragmentInstanceId";
export interface ITEndOfDataBlockEventArgs {
    targetFragmentInstanceId: TFragmentInstanceId.TFragmentInstanceId;
    targetPlanNodeId: string;
    sourceFragmentInstanceId: TFragmentInstanceId.TFragmentInstanceId;
    lastSequenceId: number;
}
export class TEndOfDataBlockEvent {
    public targetFragmentInstanceId: TFragmentInstanceId.TFragmentInstanceId;
    public targetPlanNodeId: string;
    public sourceFragmentInstanceId: TFragmentInstanceId.TFragmentInstanceId;
    public lastSequenceId: number;
    constructor(args: ITEndOfDataBlockEventArgs) {
        if (args != null && args.targetFragmentInstanceId != null) {
            this.targetFragmentInstanceId = args.targetFragmentInstanceId;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[targetFragmentInstanceId] is unset!");
        }
        if (args != null && args.targetPlanNodeId != null) {
            this.targetPlanNodeId = args.targetPlanNodeId;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[targetPlanNodeId] is unset!");
        }
        if (args != null && args.sourceFragmentInstanceId != null) {
            this.sourceFragmentInstanceId = args.sourceFragmentInstanceId;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[sourceFragmentInstanceId] is unset!");
        }
        if (args != null && args.lastSequenceId != null) {
            this.lastSequenceId = args.lastSequenceId;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[lastSequenceId] is unset!");
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("TEndOfDataBlockEvent");
        if (this.targetFragmentInstanceId != null) {
            output.writeFieldBegin("targetFragmentInstanceId", thrift.Thrift.Type.STRUCT, 1);
            this.targetFragmentInstanceId.write(output);
            output.writeFieldEnd();
        }
        if (this.targetPlanNodeId != null) {
            output.writeFieldBegin("targetPlanNodeId", thrift.Thrift.Type.STRING, 2);
            output.writeString(this.targetPlanNodeId);
            output.writeFieldEnd();
        }
        if (this.sourceFragmentInstanceId != null) {
            output.writeFieldBegin("sourceFragmentInstanceId", thrift.Thrift.Type.STRUCT, 3);
            this.sourceFragmentInstanceId.write(output);
            output.writeFieldEnd();
        }
        if (this.lastSequenceId != null) {
            output.writeFieldBegin("lastSequenceId", thrift.Thrift.Type.I32, 4);
            output.writeI32(this.lastSequenceId);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): TEndOfDataBlockEvent {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRUCT) {
                        const value_1: TFragmentInstanceId.TFragmentInstanceId = TFragmentInstanceId.TFragmentInstanceId.read(input);
                        _args.targetFragmentInstanceId = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_2: string = input.readString();
                        _args.targetPlanNodeId = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.Thrift.Type.STRUCT) {
                        const value_3: TFragmentInstanceId.TFragmentInstanceId = TFragmentInstanceId.TFragmentInstanceId.read(input);
                        _args.sourceFragmentInstanceId = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 4:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_4: number = input.readI32();
                        _args.lastSequenceId = value_4;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        if (_args.targetFragmentInstanceId !== undefined && _args.targetPlanNodeId !== undefined && _args.sourceFragmentInstanceId !== undefined && _args.lastSequenceId !== undefined) {
            return new TEndOfDataBlockEvent(_args);
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Unable to read TEndOfDataBlockEvent from input");
        }
    }
}
