/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
import * as TFragmentInstanceId from "./TFragmentInstanceId";
export interface ITFetchFragmentInstanceInfoReqArgs {
    fragmentInstanceId: TFragmentInstanceId.TFragmentInstanceId;
}
export class TFetchFragmentInstanceInfoReq {
    public fragmentInstanceId: TFragmentInstanceId.TFragmentInstanceId;
    constructor(args: ITFetchFragmentInstanceInfoReqArgs) {
        if (args != null && args.fragmentInstanceId != null) {
            this.fragmentInstanceId = args.fragmentInstanceId;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[fragmentInstanceId] is unset!");
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("TFetchFragmentInstanceInfoReq");
        if (this.fragmentInstanceId != null) {
            output.writeFieldBegin("fragmentInstanceId", thrift.Thrift.Type.STRUCT, 1);
            this.fragmentInstanceId.write(output);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): TFetchFragmentInstanceInfoReq {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRUCT) {
                        const value_1: TFragmentInstanceId.TFragmentInstanceId = TFragmentInstanceId.TFragmentInstanceId.read(input);
                        _args.fragmentInstanceId = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        if (_args.fragmentInstanceId !== undefined) {
            return new TFetchFragmentInstanceInfoReq(_args);
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Unable to read TFetchFragmentInstanceInfoReq from input");
        }
    }
}
