/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import Int64 = require("node-int64");
import * as thrift from "thrift";
export interface ITFetchTimeseriesReqArgs {
    queryBody: string;
    fetchSize?: number;
    timeout?: number | Int64;
}
export class TFetchTimeseriesReq {
    public queryBody: string;
    public fetchSize?: number;
    public timeout?: Int64;
    constructor(args: ITFetchTimeseriesReqArgs) {
        if (args != null && args.queryBody != null) {
            this.queryBody = args.queryBody;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[queryBody] is unset!");
        }
        if (args != null && args.fetchSize != null) {
            this.fetchSize = args.fetchSize;
        }
        if (args != null && args.timeout != null) {
            if (typeof args.timeout === "number") {
                this.timeout = new Int64(args.timeout);
            }
            else {
                this.timeout = args.timeout;
            }
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("TFetchTimeseriesReq");
        if (this.queryBody != null) {
            output.writeFieldBegin("queryBody", thrift.Thrift.Type.STRING, 1);
            output.writeString(this.queryBody);
            output.writeFieldEnd();
        }
        if (this.fetchSize != null) {
            output.writeFieldBegin("fetchSize", thrift.Thrift.Type.I32, 2);
            output.writeI32(this.fetchSize);
            output.writeFieldEnd();
        }
        if (this.timeout != null) {
            output.writeFieldBegin("timeout", thrift.Thrift.Type.I64, 3);
            output.writeI64(this.timeout);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): TFetchTimeseriesReq {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_1: string = input.readString();
                        _args.queryBody = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_2: number = input.readI32();
                        _args.fetchSize = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_3: Int64 = input.readI64();
                        _args.timeout = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        if (_args.queryBody !== undefined) {
            return new TFetchTimeseriesReq(_args);
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Unable to read TFetchTimeseriesReq from input");
        }
    }
}
