/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
export interface ITFireTriggerRespArgs {
    foundExecutor: boolean;
    fireResult: number;
}
export class TFireTriggerResp {
    public foundExecutor: boolean;
    public fireResult: number;
    constructor(args: ITFireTriggerRespArgs) {
        if (args != null && args.foundExecutor != null) {
            this.foundExecutor = args.foundExecutor;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[foundExecutor] is unset!");
        }
        if (args != null && args.fireResult != null) {
            this.fireResult = args.fireResult;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[fireResult] is unset!");
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("TFireTriggerResp");
        if (this.foundExecutor != null) {
            output.writeFieldBegin("foundExecutor", thrift.Thrift.Type.BOOL, 1);
            output.writeBool(this.foundExecutor);
            output.writeFieldEnd();
        }
        if (this.fireResult != null) {
            output.writeFieldBegin("fireResult", thrift.Thrift.Type.I32, 2);
            output.writeI32(this.fireResult);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): TFireTriggerResp {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_1: boolean = input.readBool();
                        _args.foundExecutor = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_2: number = input.readI32();
                        _args.fireResult = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        if (_args.foundExecutor !== undefined && _args.fireResult !== undefined) {
            return new TFireTriggerResp(_args);
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Unable to read TFireTriggerResp from input");
        }
    }
}
