/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
export interface ITFireTriggerReqArgs {
    triggerName: string;
    tablet: Buffer;
    triggerEvent: number;
}
export class TFireTriggerReq {
    public triggerName: string;
    public tablet: Buffer;
    public triggerEvent: number;
    constructor(args: ITFireTriggerReqArgs) {
        if (args != null && args.triggerName != null) {
            this.triggerName = args.triggerName;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[triggerName] is unset!");
        }
        if (args != null && args.tablet != null) {
            this.tablet = args.tablet;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[tablet] is unset!");
        }
        if (args != null && args.triggerEvent != null) {
            this.triggerEvent = args.triggerEvent;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[triggerEvent] is unset!");
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("TFireTriggerReq");
        if (this.triggerName != null) {
            output.writeFieldBegin("triggerName", thrift.Thrift.Type.STRING, 1);
            output.writeString(this.triggerName);
            output.writeFieldEnd();
        }
        if (this.tablet != null) {
            output.writeFieldBegin("tablet", thrift.Thrift.Type.STRING, 2);
            output.writeBinary(this.tablet);
            output.writeFieldEnd();
        }
        if (this.triggerEvent != null) {
            output.writeFieldBegin("triggerEvent", thrift.Thrift.Type.BYTE, 3);
            output.writeByte(this.triggerEvent);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): TFireTriggerReq {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_1: string = input.readString();
                        _args.triggerName = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_2: Buffer = input.readBinary();
                        _args.tablet = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.Thrift.Type.BYTE) {
                        const value_3: number = input.readByte();
                        _args.triggerEvent = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        if (_args.triggerName !== undefined && _args.tablet !== undefined && _args.triggerEvent !== undefined) {
            return new TFireTriggerReq(_args);
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Unable to read TFireTriggerReq from input");
        }
    }
}
