/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
export interface ITInvalidatePermissionCacheReqArgs {
    username: string;
    roleName: string;
}
export class TInvalidatePermissionCacheReq {
    public username: string;
    public roleName: string;
    constructor(args: ITInvalidatePermissionCacheReqArgs) {
        if (args != null && args.username != null) {
            this.username = args.username;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[username] is unset!");
        }
        if (args != null && args.roleName != null) {
            this.roleName = args.roleName;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[roleName] is unset!");
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("TInvalidatePermissionCacheReq");
        if (this.username != null) {
            output.writeFieldBegin("username", thrift.Thrift.Type.STRING, 1);
            output.writeString(this.username);
            output.writeFieldEnd();
        }
        if (this.roleName != null) {
            output.writeFieldBegin("roleName", thrift.Thrift.Type.STRING, 2);
            output.writeString(this.roleName);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): TInvalidatePermissionCacheReq {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_1: string = input.readString();
                        _args.username = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_2: string = input.readString();
                        _args.roleName = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        if (_args.username !== undefined && _args.roleName !== undefined) {
            return new TInvalidatePermissionCacheReq(_args);
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Unable to read TInvalidatePermissionCacheReq from input");
        }
    }
}
