/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
export interface ITInvalidateMatchedSchemaCacheReqArgs {
    pathPatternTree: Buffer;
}
export class TInvalidateMatchedSchemaCacheReq {
    public pathPatternTree: Buffer;
    constructor(args: ITInvalidateMatchedSchemaCacheReqArgs) {
        if (args != null && args.pathPatternTree != null) {
            this.pathPatternTree = args.pathPatternTree;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[pathPatternTree] is unset!");
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("TInvalidateMatchedSchemaCacheReq");
        if (this.pathPatternTree != null) {
            output.writeFieldBegin("pathPatternTree", thrift.Thrift.Type.STRING, 1);
            output.writeBinary(this.pathPatternTree);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): TInvalidateMatchedSchemaCacheReq {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_1: Buffer = input.readBinary();
                        _args.pathPatternTree = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        if (_args.pathPatternTree !== undefined) {
            return new TInvalidateMatchedSchemaCacheReq(_args);
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Unable to read TInvalidateMatchedSchemaCacheReq from input");
        }
    }
}
