/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import Int64 = require("node-int64");
import * as thrift from "thrift";
import * as org_apache_iotdb_common_rpc_thrift from "./../../../common/rpc/thrift";
export interface ITNotifyRegionMigrationReqArgs {
    logicalClock: number | Int64;
    timestamp: number | Int64;
    regionId?: org_apache_iotdb_common_rpc_thrift.TConsensusGroupId;
    isStart?: boolean;
    currentRegionOperations: Array<org_apache_iotdb_common_rpc_thrift.TConsensusGroupId>;
}
export class TNotifyRegionMigrationReq {
    public logicalClock: Int64;
    public timestamp: Int64;
    public regionId?: org_apache_iotdb_common_rpc_thrift.TConsensusGroupId;
    public isStart?: boolean;
    public currentRegionOperations: Array<org_apache_iotdb_common_rpc_thrift.TConsensusGroupId>;
    constructor(args: ITNotifyRegionMigrationReqArgs) {
        if (args != null && args.logicalClock != null) {
            if (typeof args.logicalClock === "number") {
                this.logicalClock = new Int64(args.logicalClock);
            }
            else {
                this.logicalClock = args.logicalClock;
            }
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[logicalClock] is unset!");
        }
        if (args != null && args.timestamp != null) {
            if (typeof args.timestamp === "number") {
                this.timestamp = new Int64(args.timestamp);
            }
            else {
                this.timestamp = args.timestamp;
            }
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[timestamp] is unset!");
        }
        if (args != null && args.regionId != null) {
            this.regionId = args.regionId;
        }
        if (args != null && args.isStart != null) {
            this.isStart = args.isStart;
        }
        if (args != null && args.currentRegionOperations != null) {
            this.currentRegionOperations = args.currentRegionOperations;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[currentRegionOperations] is unset!");
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("TNotifyRegionMigrationReq");
        if (this.logicalClock != null) {
            output.writeFieldBegin("logicalClock", thrift.Thrift.Type.I64, 1);
            output.writeI64(this.logicalClock);
            output.writeFieldEnd();
        }
        if (this.timestamp != null) {
            output.writeFieldBegin("timestamp", thrift.Thrift.Type.I64, 2);
            output.writeI64(this.timestamp);
            output.writeFieldEnd();
        }
        if (this.regionId != null) {
            output.writeFieldBegin("regionId", thrift.Thrift.Type.STRUCT, 3);
            this.regionId.write(output);
            output.writeFieldEnd();
        }
        if (this.isStart != null) {
            output.writeFieldBegin("isStart", thrift.Thrift.Type.BOOL, 4);
            output.writeBool(this.isStart);
            output.writeFieldEnd();
        }
        if (this.currentRegionOperations != null) {
            output.writeFieldBegin("currentRegionOperations", thrift.Thrift.Type.LIST, 5);
            output.writeListBegin(thrift.Thrift.Type.STRUCT, this.currentRegionOperations.length);
            this.currentRegionOperations.forEach((value_1: org_apache_iotdb_common_rpc_thrift.TConsensusGroupId): void => {
                value_1.write(output);
            });
            output.writeListEnd();
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): TNotifyRegionMigrationReq {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_2: Int64 = input.readI64();
                        _args.logicalClock = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_3: Int64 = input.readI64();
                        _args.timestamp = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.Thrift.Type.STRUCT) {
                        const value_4: org_apache_iotdb_common_rpc_thrift.TConsensusGroupId = org_apache_iotdb_common_rpc_thrift.TConsensusGroupId.read(input);
                        _args.regionId = value_4;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 4:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_5: boolean = input.readBool();
                        _args.isStart = value_5;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 5:
                    if (fieldType === thrift.Thrift.Type.LIST) {
                        const value_6: Array<org_apache_iotdb_common_rpc_thrift.TConsensusGroupId> = new Array<org_apache_iotdb_common_rpc_thrift.TConsensusGroupId>();
                        const metadata_1: thrift.TList = input.readListBegin();
                        const size_1: number = metadata_1.size;
                        for (let i_1: number = 0; i_1 < size_1; i_1++) {
                            const value_7: org_apache_iotdb_common_rpc_thrift.TConsensusGroupId = org_apache_iotdb_common_rpc_thrift.TConsensusGroupId.read(input);
                            value_6.push(value_7);
                        }
                        input.readListEnd();
                        _args.currentRegionOperations = value_6;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        if (_args.logicalClock !== undefined && _args.timestamp !== undefined && _args.currentRegionOperations !== undefined) {
            return new TNotifyRegionMigrationReq(_args);
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Unable to read TNotifyRegionMigrationReq from input");
        }
    }
}
