/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
export interface ITPushMultiTopicMetaReqArgs {
    topicMetas?: Array<Buffer>;
    topicNamesToDrop?: Array<string>;
}
export class TPushMultiTopicMetaReq {
    public topicMetas?: Array<Buffer>;
    public topicNamesToDrop?: Array<string>;
    constructor(args?: ITPushMultiTopicMetaReqArgs) {
        if (args != null && args.topicMetas != null) {
            this.topicMetas = args.topicMetas;
        }
        if (args != null && args.topicNamesToDrop != null) {
            this.topicNamesToDrop = args.topicNamesToDrop;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("TPushMultiTopicMetaReq");
        if (this.topicMetas != null) {
            output.writeFieldBegin("topicMetas", thrift.Thrift.Type.LIST, 1);
            output.writeListBegin(thrift.Thrift.Type.STRING, this.topicMetas.length);
            this.topicMetas.forEach((value_1: Buffer): void => {
                output.writeBinary(value_1);
            });
            output.writeListEnd();
            output.writeFieldEnd();
        }
        if (this.topicNamesToDrop != null) {
            output.writeFieldBegin("topicNamesToDrop", thrift.Thrift.Type.LIST, 2);
            output.writeListBegin(thrift.Thrift.Type.STRING, this.topicNamesToDrop.length);
            this.topicNamesToDrop.forEach((value_2: string): void => {
                output.writeString(value_2);
            });
            output.writeListEnd();
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): TPushMultiTopicMetaReq {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.LIST) {
                        const value_3: Array<Buffer> = new Array<Buffer>();
                        const metadata_1: thrift.TList = input.readListBegin();
                        const size_1: number = metadata_1.size;
                        for (let i_1: number = 0; i_1 < size_1; i_1++) {
                            const value_4: Buffer = input.readBinary();
                            value_3.push(value_4);
                        }
                        input.readListEnd();
                        _args.topicMetas = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.LIST) {
                        const value_5: Array<string> = new Array<string>();
                        const metadata_2: thrift.TList = input.readListBegin();
                        const size_2: number = metadata_2.size;
                        for (let i_2: number = 0; i_2 < size_2; i_2++) {
                            const value_6: string = input.readString();
                            value_5.push(value_6);
                        }
                        input.readListEnd();
                        _args.topicNamesToDrop = value_5;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new TPushMultiTopicMetaReq(_args);
    }
}
