/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
export interface ITPushPipeMetaReqArgs {
    pipeMetas: Array<Buffer>;
}
export class TPushPipeMetaReq {
    public pipeMetas: Array<Buffer>;
    constructor(args: ITPushPipeMetaReqArgs) {
        if (args != null && args.pipeMetas != null) {
            this.pipeMetas = args.pipeMetas;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[pipeMetas] is unset!");
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("TPushPipeMetaReq");
        if (this.pipeMetas != null) {
            output.writeFieldBegin("pipeMetas", thrift.Thrift.Type.LIST, 1);
            output.writeListBegin(thrift.Thrift.Type.STRING, this.pipeMetas.length);
            this.pipeMetas.forEach((value_1: Buffer): void => {
                output.writeBinary(value_1);
            });
            output.writeListEnd();
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): TPushPipeMetaReq {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.LIST) {
                        const value_2: Array<Buffer> = new Array<Buffer>();
                        const metadata_1: thrift.TList = input.readListBegin();
                        const size_1: number = metadata_1.size;
                        for (let i_1: number = 0; i_1 < size_1; i_1++) {
                            const value_3: Buffer = input.readBinary();
                            value_2.push(value_3);
                        }
                        input.readListEnd();
                        _args.pipeMetas = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        if (_args.pipeMetas !== undefined) {
            return new TPushPipeMetaReq(_args);
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Unable to read TPushPipeMetaReq from input");
        }
    }
}
