/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
import * as org_apache_iotdb_common_rpc_thrift from "./../../../common/rpc/thrift";
export interface ITResetPeerListReqArgs {
    regionId: org_apache_iotdb_common_rpc_thrift.TConsensusGroupId;
    correctLocations: Array<org_apache_iotdb_common_rpc_thrift.TDataNodeLocation>;
}
export class TResetPeerListReq {
    public regionId: org_apache_iotdb_common_rpc_thrift.TConsensusGroupId;
    public correctLocations: Array<org_apache_iotdb_common_rpc_thrift.TDataNodeLocation>;
    constructor(args: ITResetPeerListReqArgs) {
        if (args != null && args.regionId != null) {
            this.regionId = args.regionId;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[regionId] is unset!");
        }
        if (args != null && args.correctLocations != null) {
            this.correctLocations = args.correctLocations;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[correctLocations] is unset!");
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("TResetPeerListReq");
        if (this.regionId != null) {
            output.writeFieldBegin("regionId", thrift.Thrift.Type.STRUCT, 1);
            this.regionId.write(output);
            output.writeFieldEnd();
        }
        if (this.correctLocations != null) {
            output.writeFieldBegin("correctLocations", thrift.Thrift.Type.LIST, 2);
            output.writeListBegin(thrift.Thrift.Type.STRUCT, this.correctLocations.length);
            this.correctLocations.forEach((value_1: org_apache_iotdb_common_rpc_thrift.TDataNodeLocation): void => {
                value_1.write(output);
            });
            output.writeListEnd();
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): TResetPeerListReq {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRUCT) {
                        const value_2: org_apache_iotdb_common_rpc_thrift.TConsensusGroupId = org_apache_iotdb_common_rpc_thrift.TConsensusGroupId.read(input);
                        _args.regionId = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.LIST) {
                        const value_3: Array<org_apache_iotdb_common_rpc_thrift.TDataNodeLocation> = new Array<org_apache_iotdb_common_rpc_thrift.TDataNodeLocation>();
                        const metadata_1: thrift.TList = input.readListBegin();
                        const size_1: number = metadata_1.size;
                        for (let i_1: number = 0; i_1 < size_1; i_1++) {
                            const value_4: org_apache_iotdb_common_rpc_thrift.TDataNodeLocation = org_apache_iotdb_common_rpc_thrift.TDataNodeLocation.read(input);
                            value_3.push(value_4);
                        }
                        input.readListEnd();
                        _args.correctLocations = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        if (_args.regionId !== undefined && _args.correctLocations !== undefined) {
            return new TResetPeerListReq(_args);
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Unable to read TResetPeerListReq from input");
        }
    }
}
