/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
export interface ITSchemaFetchRequestArgs {
    serializedPathPatternTree: Buffer;
    isPrefixMatchPath: boolean;
}
export class TSchemaFetchRequest {
    public serializedPathPatternTree: Buffer;
    public isPrefixMatchPath: boolean;
    constructor(args: ITSchemaFetchRequestArgs) {
        if (args != null && args.serializedPathPatternTree != null) {
            this.serializedPathPatternTree = args.serializedPathPatternTree;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[serializedPathPatternTree] is unset!");
        }
        if (args != null && args.isPrefixMatchPath != null) {
            this.isPrefixMatchPath = args.isPrefixMatchPath;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[isPrefixMatchPath] is unset!");
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("TSchemaFetchRequest");
        if (this.serializedPathPatternTree != null) {
            output.writeFieldBegin("serializedPathPatternTree", thrift.Thrift.Type.STRING, 1);
            output.writeBinary(this.serializedPathPatternTree);
            output.writeFieldEnd();
        }
        if (this.isPrefixMatchPath != null) {
            output.writeFieldBegin("isPrefixMatchPath", thrift.Thrift.Type.BOOL, 2);
            output.writeBool(this.isPrefixMatchPath);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): TSchemaFetchRequest {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_1: Buffer = input.readBinary();
                        _args.serializedPathPatternTree = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_2: boolean = input.readBool();
                        _args.isPrefixMatchPath = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        if (_args.serializedPathPatternTree !== undefined && _args.isPrefixMatchPath !== undefined) {
            return new TSchemaFetchRequest(_args);
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Unable to read TSchemaFetchRequest from input");
        }
    }
}
