/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
import * as TSendSinglePlanNodeReq from "./TSendSinglePlanNodeReq";
export interface ITSendBatchPlanNodeReqArgs {
    requests: Array<TSendSinglePlanNodeReq.TSendSinglePlanNodeReq>;
}
export class TSendBatchPlanNodeReq {
    public requests: Array<TSendSinglePlanNodeReq.TSendSinglePlanNodeReq>;
    constructor(args: ITSendBatchPlanNodeReqArgs) {
        if (args != null && args.requests != null) {
            this.requests = args.requests;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[requests] is unset!");
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("TSendBatchPlanNodeReq");
        if (this.requests != null) {
            output.writeFieldBegin("requests", thrift.Thrift.Type.LIST, 1);
            output.writeListBegin(thrift.Thrift.Type.STRUCT, this.requests.length);
            this.requests.forEach((value_1: TSendSinglePlanNodeReq.TSendSinglePlanNodeReq): void => {
                value_1.write(output);
            });
            output.writeListEnd();
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): TSendBatchPlanNodeReq {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.LIST) {
                        const value_2: Array<TSendSinglePlanNodeReq.TSendSinglePlanNodeReq> = new Array<TSendSinglePlanNodeReq.TSendSinglePlanNodeReq>();
                        const metadata_1: thrift.TList = input.readListBegin();
                        const size_1: number = metadata_1.size;
                        for (let i_1: number = 0; i_1 < size_1; i_1++) {
                            const value_3: TSendSinglePlanNodeReq.TSendSinglePlanNodeReq = TSendSinglePlanNodeReq.TSendSinglePlanNodeReq.read(input);
                            value_2.push(value_3);
                        }
                        input.readListEnd();
                        _args.requests = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        if (_args.requests !== undefined) {
            return new TSendBatchPlanNodeReq(_args);
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Unable to read TSendBatchPlanNodeReq from input");
        }
    }
}
