/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
import * as org_apache_iotdb_common_rpc_thrift from "./../../../common/rpc/thrift";
export interface ITTableDeviceDeletionWithPatternOrModReqArgs {
    regionIdList: Array<org_apache_iotdb_common_rpc_thrift.TConsensusGroupId>;
    tableName: string;
    patternOrModInfo: Buffer;
}
export class TTableDeviceDeletionWithPatternOrModReq {
    public regionIdList: Array<org_apache_iotdb_common_rpc_thrift.TConsensusGroupId>;
    public tableName: string;
    public patternOrModInfo: Buffer;
    constructor(args: ITTableDeviceDeletionWithPatternOrModReqArgs) {
        if (args != null && args.regionIdList != null) {
            this.regionIdList = args.regionIdList;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[regionIdList] is unset!");
        }
        if (args != null && args.tableName != null) {
            this.tableName = args.tableName;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[tableName] is unset!");
        }
        if (args != null && args.patternOrModInfo != null) {
            this.patternOrModInfo = args.patternOrModInfo;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[patternOrModInfo] is unset!");
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("TTableDeviceDeletionWithPatternOrModReq");
        if (this.regionIdList != null) {
            output.writeFieldBegin("regionIdList", thrift.Thrift.Type.LIST, 1);
            output.writeListBegin(thrift.Thrift.Type.STRUCT, this.regionIdList.length);
            this.regionIdList.forEach((value_1: org_apache_iotdb_common_rpc_thrift.TConsensusGroupId): void => {
                value_1.write(output);
            });
            output.writeListEnd();
            output.writeFieldEnd();
        }
        if (this.tableName != null) {
            output.writeFieldBegin("tableName", thrift.Thrift.Type.STRING, 2);
            output.writeString(this.tableName);
            output.writeFieldEnd();
        }
        if (this.patternOrModInfo != null) {
            output.writeFieldBegin("patternOrModInfo", thrift.Thrift.Type.STRING, 3);
            output.writeBinary(this.patternOrModInfo);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): TTableDeviceDeletionWithPatternOrModReq {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.LIST) {
                        const value_2: Array<org_apache_iotdb_common_rpc_thrift.TConsensusGroupId> = new Array<org_apache_iotdb_common_rpc_thrift.TConsensusGroupId>();
                        const metadata_1: thrift.TList = input.readListBegin();
                        const size_1: number = metadata_1.size;
                        for (let i_1: number = 0; i_1 < size_1; i_1++) {
                            const value_3: org_apache_iotdb_common_rpc_thrift.TConsensusGroupId = org_apache_iotdb_common_rpc_thrift.TConsensusGroupId.read(input);
                            value_2.push(value_3);
                        }
                        input.readListEnd();
                        _args.regionIdList = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_4: string = input.readString();
                        _args.tableName = value_4;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_5: Buffer = input.readBinary();
                        _args.patternOrModInfo = value_5;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        if (_args.regionIdList !== undefined && _args.tableName !== undefined && _args.patternOrModInfo !== undefined) {
            return new TTableDeviceDeletionWithPatternOrModReq(_args);
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Unable to read TTableDeviceDeletionWithPatternOrModReq from input");
        }
    }
}
