/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import Int64 = require("node-int64");
import * as thrift from "thrift";
export interface ITSCloseOperationReqArgs {
    sessionId: number | Int64;
    queryId?: number | Int64;
    statementId?: number | Int64;
}
export class TSCloseOperationReq {
    public sessionId: Int64;
    public queryId?: Int64;
    public statementId?: Int64;
    constructor(args: ITSCloseOperationReqArgs) {
        if (args != null && args.sessionId != null) {
            if (typeof args.sessionId === "number") {
                this.sessionId = new Int64(args.sessionId);
            }
            else {
                this.sessionId = args.sessionId;
            }
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[sessionId] is unset!");
        }
        if (args != null && args.queryId != null) {
            if (typeof args.queryId === "number") {
                this.queryId = new Int64(args.queryId);
            }
            else {
                this.queryId = args.queryId;
            }
        }
        if (args != null && args.statementId != null) {
            if (typeof args.statementId === "number") {
                this.statementId = new Int64(args.statementId);
            }
            else {
                this.statementId = args.statementId;
            }
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("TSCloseOperationReq");
        if (this.sessionId != null) {
            output.writeFieldBegin("sessionId", thrift.Thrift.Type.I64, 1);
            output.writeI64(this.sessionId);
            output.writeFieldEnd();
        }
        if (this.queryId != null) {
            output.writeFieldBegin("queryId", thrift.Thrift.Type.I64, 2);
            output.writeI64(this.queryId);
            output.writeFieldEnd();
        }
        if (this.statementId != null) {
            output.writeFieldBegin("statementId", thrift.Thrift.Type.I64, 3);
            output.writeI64(this.statementId);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): TSCloseOperationReq {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_1: Int64 = input.readI64();
                        _args.sessionId = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_2: Int64 = input.readI64();
                        _args.queryId = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_3: Int64 = input.readI64();
                        _args.statementId = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        if (_args.sessionId !== undefined) {
            return new TSCloseOperationReq(_args);
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Unable to read TSCloseOperationReq from input");
        }
    }
}
