/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import Int64 = require("node-int64");
import * as thrift from "thrift";
export interface ITSyncTransportMetaInfoArgs {
    fileName: string;
    startIndex: number | Int64;
}
export class TSyncTransportMetaInfo {
    public fileName: string;
    public startIndex: Int64;
    constructor(args: ITSyncTransportMetaInfoArgs) {
        if (args != null && args.fileName != null) {
            this.fileName = args.fileName;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[fileName] is unset!");
        }
        if (args != null && args.startIndex != null) {
            if (typeof args.startIndex === "number") {
                this.startIndex = new Int64(args.startIndex);
            }
            else {
                this.startIndex = args.startIndex;
            }
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[startIndex] is unset!");
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("TSyncTransportMetaInfo");
        if (this.fileName != null) {
            output.writeFieldBegin("fileName", thrift.Thrift.Type.STRING, 1);
            output.writeString(this.fileName);
            output.writeFieldEnd();
        }
        if (this.startIndex != null) {
            output.writeFieldBegin("startIndex", thrift.Thrift.Type.I64, 2);
            output.writeI64(this.startIndex);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): TSyncTransportMetaInfo {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_1: string = input.readString();
                        _args.fileName = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_2: Int64 = input.readI64();
                        _args.startIndex = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        if (_args.fileName !== undefined && _args.startIndex !== undefined) {
            return new TSyncTransportMetaInfo(_args);
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Unable to read TSyncTransportMetaInfo from input");
        }
    }
}
